# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      # use `-browsers` prefix for selenium tests, e.g. `3.6.1-browsers`
        - image: ubuntu:16.04

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/postgres:9.4

    working_directory: ~/mhn

    steps:
      - checkout

      - run:
          name: install mhn
          command: |
            apt-get update && \
            apt-get -y install sudo && \
            apt-get -y install lsb-release && \
            apt-get -y install apt-transport-https
            sudo ./install.sh

